require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'WHO_App' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'toolbar-android', :path => '../node_modules/@react-native-community/toolbar-android'

  pod 'RNDateTimePicker', :path => '../node_modules/@react-native-community/datetimepicker'

  #pod 'ReactNativeCountries', :path => '../node_modules/react-native-countries'

  

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  target 'WHO_AppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'WHO_App-tvOS' do
  # Pods for WHO_App-tvOS

  target 'WHO_App-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
