/* eslint-disable prettier/prettier */
import {StyleSheet} from 'react-native';
import {
  responsiveHeight,
  responsiveWidth,
  responsiveFontSize,
} from 'react-native-responsive-dimensions';
export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    height: '100%',
    width: '100%',
  },
  view: {
    backgroundColor: '#FFFFFF',
  },
  view2: {
    flex: 0.09,
    backgroundColor: '#0072BB',
    width: responsiveWidth(100),
  },
  text_prg: {
    color: '#FFFFFF',
    fontFamily: 'SF-Medium',
    fontSize: responsiveFontSize(2.5),
    marginTop: responsiveHeight(1),
    marginLeft: responsiveWidth(34),
  },
  arrow: {
    width: responsiveWidth(3),
    height: responsiveHeight(4),
    marginLeft: responsiveWidth(5),
    marginTop: responsiveHeight(0.75),
    resizeMode: 'contain',
  },
  cardview: {
    backgroundColor: '#CBE2F1',
    marginTop: responsiveHeight(2),
    marginLeft: responsiveWidth(5.5),
    width: responsiveWidth(90),
  },
  cardview4: {
    flex: 1,
    backgroundColor: '#CBE2F1',
    marginTop: responsiveHeight(0.25),
    marginLeft: responsiveWidth(8),
    width: responsiveWidth(85),
    bottom: responsiveHeight(0.25),
  },
  cardview5: {
    flex: 0.4,
    backgroundColor: '#CBE2F1',
    marginTop: responsiveHeight(2),
    marginLeft: responsiveWidth(8),
    width: responsiveWidth(85),
  },
  card_text1: {
    padding: 0,
    margin: 10,
    color: '#0072BB',
    fontFamily: 'SF-Bold',
    marginLeft: responsiveWidth(3),
  },
  card_text2: {
    color: '#202020',
    fontSize: responsiveFontSize(2),
    fontFamily: 'SF-Regular',
    marginLeft: responsiveWidth(3),
    marginTop: responsiveHeight(0),
    width: responsiveWidth(50),
  },
  card_text3: {
    color: '#202020',
    fontSize: responsiveFontSize(2),
    fontFamily: 'SF-Bold',
    marginLeft: responsiveWidth(3),
    marginTop: responsiveHeight(1),
    fontWeight: 'bold',
  },
  square: {
    width: responsiveWidth(22),
    height: responsiveHeight(12),
    borderRadius: 100 / 5,
    backgroundColor: '#FFFFFF',
    opacity: 100,
    marginBottom: responsiveHeight(3),
    marginTop: responsiveHeight(4),
    marginLeft: responsiveWidth(4),
    marginRight: responsiveWidth(2),
  },
  image: {
    resizeMode: 'contain',
    marginTop: responsiveHeight(3),
    marginLeft: responsiveWidth(4),
    width: responsiveWidth(15),
    height: responsiveHeight(7),
    // marginRight: responsiveWidth(-20),
  },
  buttonContainer1: {
    height: responsiveHeight(6.5),
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: responsiveHeight(-8),
    marginLeft: responsiveHeight(7),
    width: responsiveWidth(70),
    borderRadius: 30,
  },
  loginButton: {
    backgroundColor: '#0072BB',
  },
  loginText: {
    color: '#FFFFFF',
    fontFamily: 'SF-Medium',
    fontSize: responsiveFontSize(2),
  },
  container2: {
    flex: 0.6,
    backgroundColor: '#FFFFFF',
    // height: responsiveHeight(20),
    width: responsiveWidth(100),
    marginTop: responsiveHeight(1),
    paddingBottom: 10,
  },
});
