/* eslint-disable prettier/prettier */
import {StyleSheet} from 'react-native';
import {
  responsiveHeight,
  responsiveWidth,
  responsiveFontSize,
} from 'react-native-responsive-dimensions';
import { blockMarginHalf,blockMargin } from '../ui/common/responsive';
export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    height: '100%',
    width: '100%',
  },
  view: {
    width:'100%',
    height: '100%',
    backgroundColor: '#FFFFFF',
  },
  scrollview: {
    height: '100%',
  },
  view2: {
   
    backgroundColor: '#FFFFFF',
    marginTop: blockMargin,
    alignItems: 'center',
    marginBottom: blockMargin
  },
  view3: {
    
    backgroundColor: '#0072BB',
    marginTop: blockMargin,
    marginBottom: blockMargin,
    alignItems: 'center',
  },
  motivation_view: {
    backgroundColor: '#0072BB',
    marginTop: blockMargin,
    width: responsiveWidth(100),
  },
  table_view: {
    backgroundColor: '#0072BB',
    marginTop: responsiveHeight(2),
    width: responsiveWidth(100),
    height: responsiveHeight(35),
  },
  containerToolbar: {
    justifyContent: 'center',
    // https://github.com/facebook/react-native/issues/2957#event-417214498
    alignItems: 'center',
    backgroundColor: '#0072BB',
  },
  toolbar: {
    backgroundColor: '#0072BB',
    height: responsiveHeight(9),
    width: responsiveWidth(100),
  },
  toolbar_title: {
    color: '#FFFFFF',
    fontFamily: 'SF-Medium',
    fontSize: responsiveFontSize(2.5),
    alignContent: 'center',
  },
  text: {
    textAlign: 'center',
    color: '#202020',
    fontFamily: 'SF-Medium',
    fontSize: responsiveFontSize(2),
    marginTop: responsiveHeight(1),
    marginLeft: responsiveWidth(25),
  },
  buttonContainer: {
    height: responsiveHeight(6.5),
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: responsiveHeight(0),
    marginLeft: responsiveHeight(1),
    width: responsiveWidth(45),
    borderRadius: 30,
  },
  submitbutton: {
    backgroundColor: '#0072BB',
  },
  submitbutton1: {
    backgroundColor: '#FFFFFF',
  },
  submittext: {
    color: '#FFFFFF',
    fontFamily: 'SF-Medium',
    fontSize: responsiveFontSize(2),
    alignItems: 'center',
  },
  submittext1: {
    color: '#0072BB',
    fontFamily: 'SF-Medium',
    fontSize: responsiveFontSize(2),
    alignItems: 'center',
    fontWeight: 'bold',
  },
  share_img: {
    resizeMode: 'contain',
    width: 25,
    height: 25,

    marginLeft: responsiveWidth(20),
    marginTop: responsiveHeight(0.7),
  },
  share_img3: {
    resizeMode: 'contain',
    width: 25,
    height: 25,
    tintColor: '#fff',
    marginLeft: responsiveWidth(32),
    marginTop: responsiveHeight(0.7),
  },
  clock: {
    marginLeft: responsiveWidth(10),
  },
  head_text: {
    color: '#0072BB',
    fontSize: responsiveFontSize(2),
    textAlign: 'center',
    fontFamily: 'SF-Medium',
    marginTop: responsiveHeight(2),
  },
  cardview: {
    backgroundColor: '#CBE2F1',
    marginTop: responsiveHeight(2),
    justifyContent: 'center',
    width: '90%',padding: blockMarginHalf
  },
  cardview1: {
    backgroundColor: '#0072BB',
    marginTop: blockMarginHalf,
    width: '90%',
  },
  cardview2: {
    backgroundColor: '#FFFFFF',
    marginTop: responsiveHeight(2),
    marginLeft: responsiveWidth(5.5),
    width: '90%',
  },
  card_text1: {
    padding: 0,
    margin: 10,
    color: '#0072BB',
    fontFamily: 'SF-Medium',
    marginLeft: responsiveWidth(3),
  },
  card_text2: {
    color: '#202020',
    fontSize: responsiveFontSize(2),
    fontFamily: 'SF-Regular',
    marginLeft: responsiveWidth(3),
    marginTop: responsiveHeight(0),
  },
  card_text4: {
    color: '#202020',
    fontSize: responsiveFontSize(2),
    fontFamily: 'SF-Regular',
    marginLeft: responsiveWidth(1.5),
    marginRight: responsiveWidth(2.5),
    marginTop: responsiveHeight(0),
  },
  card_text3: {
    padding: 0,
    margin: 10,
    color: '#0072BB',
    fontFamily: 'SF-Medium',
    fontWeight: 'bold',
    marginLeft: responsiveWidth(1),
  },
  // card_text5:{
  //   padding: 0,
  //   margin: 10,
  //   fontFamily: 'SF Display',
  //   color: '#FFFFFF',
  //   fontWeight: 'bold',
  //   fontSize: responsiveFontSize(2.5),
  //   marginLeft: responsiveWidth(32),
  // },
  card_text6: {
    textAlign: 'center',
    width: '50%',
    fontFamily: 'SF-Medium',
    color: '#FFFFFF',
    alignSelf: 'center',
    justifyContent: 'center',
    fontSize: responsiveFontSize(2),
  },
  card_text7: {
    textAlign: 'center',
    width: '50%',
    fontFamily: 'SF-Medium',
    color: '#FFFFFF',
    alignSelf: 'center',
    justifyContent: 'center',
    fontSize: responsiveFontSize(2),
  },
  card_text8: {
    textAlign: 'center',
    width: '50%',
    fontFamily: 'SF-Bold',
    color: '#FFFFFF',
    alignSelf: 'center',
    justifyContent: 'center',
    fontSize: responsiveFontSize(2.5),

    fontWeight: 'bold',
  },
  card_text9: {
    textAlign: 'center',
    justifyContent: 'center',
    width: '50%',
    fontFamily: 'SF-Bold',
    color: '#FFFFFF',

    fontSize: responsiveFontSize(2.5),

    fontWeight: 'bold',
  },
  card_text10: {
    color: '#202020',
    fontSize: responsiveFontSize(2),
    fontFamily: 'SF-Regular',
    marginLeft: responsiveWidth(1),
    marginRight: responsiveWidth(1),
    marginTop: responsiveHeight(0),
    marginBottom: responsiveHeight(3),
  },
  card_text11: {
    color: '#202020',
    fontSize: responsiveFontSize(2),
    fontFamily: 'SF-Regular',
    marginLeft: responsiveWidth(3),
    marginTop: responsiveHeight(0),
    marginBottom: responsiveHeight(1),
  },
  card_text13: {
    color: '#202020',
    fontSize: responsiveFontSize(2.5),
    fontFamily: 'SF-Bold',
    textAlign: 'center',
    //  marginLeft: responsiveWidth(3),
    marginTop: responsiveHeight(0),
    marginBottom: responsiveHeight(1),
  },
  card_text14: {
    padding: 0,
    margin: 2,
    color: '#0072BB',
    fontFamily: 'SF-Medium',
    // marginLeft: responsiveWidth(3),
    textAlign: 'center',
  },
  card_text15: {
    color: '#202020',
    fontSize: responsiveFontSize(2.5),
    fontFamily: 'SF-Bold',
    textAlign: 'center',
    //  marginLeft: responsiveWidth(3),
    marginTop: responsiveHeight(0),
    marginBottom: responsiveHeight(1),
  },
  card_text16: {
    padding: 0,
    margin: 8,
    color: '#0072BB',
    // marginLeft: responsiveWidth(3),
    fontFamily: 'SF-Medium',
    textAlign: 'center',
  },
  circle: {
    width: responsiveWidth(16),
    height: responsiveHeight(8),
    borderRadius: 100 / 2,
    backgroundColor: '#FFFFFF',
    opacity: 100,
    end: 0,
    justifyContent: 'center',
    marginBottom: responsiveHeight(3),
    marginTop: responsiveHeight(3),
    marginLeft: responsiveWidth(2),
    marginRight: responsiveWidth(2),
  },
  heart: {
    resizeMode: 'contain',
    marginTop: responsiveHeight(2.5),
    marginLeft: responsiveWidth(4),
  },
  blood: {
    resizeMode: 'contain',
    marginTop: responsiveHeight(2),
    marginLeft: responsiveWidth(5.3),
  },
  square: {
    width: responsiveWidth(20),
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    marginTop: responsiveHeight(2),
    marginLeft: responsiveWidth(2),
    marginBottom: responsiveHeight(2),
    marginRight: responsiveWidth(2),
    padding: 10,
  },
  report: {
    resizeMode: 'contain',
    width: '100%',
  },
  square1: {
    width: responsiveWidth(23),
    height: responsiveHeight(11),
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    marginTop: responsiveHeight(6),
    marginLeft: responsiveWidth(4),
    marginBottom: responsiveHeight(2),
    marginRight: responsiveWidth(2),
    padding: 10,
  },
  bike: {
    resizeMode: 'contain',
    width: '100%',
  },
  text_mid: {
    textAlign: 'center',
    color: '#0072BB',
    fontFamily: 'SF-Medium',
    fontSize: responsiveFontSize(2),
    marginTop: responsiveHeight(1),
    marginLeft: responsiveWidth(15),
  },
  share_img1: {
    resizeMode: 'contain',
    width: 25,
    height: 25,
    marginLeft: responsiveWidth(9.5),
    marginTop: responsiveHeight(0.7),
  },
  text2: {
    textAlign: 'center',
    color: '#202020',
    fontFamily: 'SF-Regular',
    fontSize: responsiveFontSize(1.75),
    marginTop: responsiveHeight(1),
    marginLeft: responsiveWidth(3),
    marginRight: responsiveWidth(3),
    lineHeight: responsiveFontSize(2.75),
  },
  share_img2: {
    resizeMode: 'contain',
    width: 25,
    height: 25,
    marginLeft: responsiveWidth(15),
    marginTop: responsiveHeight(0.7),
  },
  text_prg: {
    textAlign: 'center',
    color: '#0072BB',
    fontFamily: 'SF-Medium',
    fontSize: responsiveFontSize(2),
    marginTop: responsiveHeight(1),
    marginLeft: responsiveWidth(28),
  },
  text3: {
    textAlign: 'center',
    color: '#FFFFFF',
    fontFamily: 'SF-Medium',
    fontSize: responsiveFontSize(2.5),
    marginTop: responsiveHeight(2),
    // marginLeft: responsiveWidth(24),
    fontWeight: '700',
  },
  text4: {
    textAlign: 'center',
    color: '#FFFFFF',
    fontFamily: 'SF-Regular',
    fontSize: responsiveFontSize(2),
    marginTop: responsiveHeight(2),
    padding: 5,
    // marginLeft: responsiveWidth(24),
  },
  text5: {
    textAlign: 'center',
    color: '#FFFFFF',
    fontFamily: 'SF-Medium',
    fontSize: responsiveFontSize(2.5),
    marginTop: responsiveHeight(1),
    marginLeft: responsiveWidth(4),
  },
  text_crv: {
    textAlign: 'center',
    color: '#0072BB',
    fontFamily: 'SF-Medium',
    fontSize: responsiveFontSize(2),
    marginTop: responsiveHeight(2.5),
    fontWeight: 'bold',
  },
  badge1: {
    resizeMode: 'contain',
    width: 105,
    height: 105,
    justifyContent: 'center',

    marginTop: responsiveHeight(1),
  },
  badge2: {
    resizeMode: 'contain',
    width: 105,
    height: 105,

    marginTop: responsiveHeight(1),
  },
  text_tab: {
    color: '#FFFFFF',
    marginLeft: responsiveWidth(6),
    marginBottom: responsiveHeight(2),
    marginTop: responsiveHeight(0.5),
  },
  text_head: {
    color: '#0072BB',
    marginLeft: responsiveWidth(6),
    margin: responsiveWidth(2),
  },
  header: {width: '100%', height: '25%', backgroundColor: '#CBE2F1'},
  fab: {
    height: responsiveHeight(8),
    width: responsiveWidth(16),
    borderRadius: 100 / 2,
    borderStyle: 'dotted',
    position: 'absolute',
    bottom: responsiveHeight(2),
    // right: responsiveWidth(5),
    marginLeft: responsiveWidth(40),
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#0072BB',
    borderWidth: 2,
    borderColor: '#CBE2F1',
    marginTop: 5,
  },
  text_fab: {
    fontSize: responsiveFontSize(4),
    color: 'white',
  },
  fab1: {
    height: responsiveHeight(7),
    width: responsiveWidth(14),
    borderRadius: 100 / 2,
    borderStyle: 'dotted',
    position: 'absolute',
    top: responsiveHeight(0),
    right: responsiveWidth(4),
    // marginLeft: responsiveWidth(76),
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1.8,
    borderColor: '#0072BB',
  },
  text_fab1: {
    fontSize: responsiveFontSize(3.5),
    color: '#0072BB',
  },
  arrow: {
    width: responsiveWidth(3),
    height: responsiveHeight(4),
    marginLeft: responsiveWidth(6),
    resizeMode: 'contain',
  },
  more: {
    width: responsiveWidth(3),
    height: responsiveHeight(2.5),
    marginLeft: responsiveWidth(29),
    resizeMode: 'contain',
  },
  menu: {
    width: responsiveWidth(45),
    height: responsiveHeight(15),
    marginTop: responsiveHeight(5),
    marginRight: responsiveWidth(25),
    backgroundColor: '#CBE2F1',
  },
});
